version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "8000:80"
  backend:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql1
    networks:
          database:
            aliases:
              - mssql1
    environment:
      MSSQL_SA_PASSWORD: "hum-2977"
      ACCEPT_EULA: "Y"
    ports:
      - "1440:1433"